### ISSUE TITLE
benchmark comparisons

### ISSUE THREAD

**Issue by gideonite** [BioJulia/Bio.jl#121] opened 2015-11-12 02:59 UTC
Hi everyone,

Has anyone specifically bench marked BioJulia against other libraries commonly used in the field of bioinformatics? I think that having such stats would be very useful.

Thanks,
Gideon.

**Comment by bicycle1885** [comment] 2015-11-12 04:19
You can find some benchmarks (vs. SeqAn and Bioconductor) in JuliaCon's talk by @dcjones  (https://github.com/BioJulia/talks/blob/master/juliacon2015/BioJulia%20Talk.ipynb).

I also did for pairwise alignment algorithms (#111). Here is the benchmark script:

```julia
affinegap = AffineGapScoreModel(BLOSUM62, -10, -1)
a = first(open("Q8WZ42.fasta", FASTA)).seq
b = first(open("A2ASS6.fasta", FASTA)).seq
@time aln = pairalign(
    GlobalAlignment(),
    convert(Vector{AminoAcid}, a),
    convert(Vector{AminoAcid}, b),
    affinegap,
)
println(score(aln))
```

```
8.012499 seconds (601.99 k allocations: 1.155 GB, 0.09% gc time)
165611
```

vs. R (Biostrings):
```
   user  system elapsed
 14.042   1.233  15.475
```

But more comprehensive benchmark suite may need to be added to show off the potential of Julia and avoid performance regressions.

**Comment by Ward9250** [comment] 2015-11-12 08:52
I wonder if there is a possibility of combining timing with tests, so we can get a readout of test success  in addition to how long they took to perform.

**Comment by dcjones** [comment] 2015-11-12 18:54
We might be better off just running benchmarks manually. Running them on travis has some disadvantages: tests would take much longer to run, benchmarks may run on different hardware and with different background processes each time, and some of the benchmarks require downloading a large example dataset and installing and running other tools to compare against.

**Comment by gideonite** [comment] 2015-11-12 19:04
The reason I brought this is up is mostly so that I can convince my colleagues that Julia is fast enough. Doing the benchmarks for BioJulia specifically is really just to put the nail in the coffin. In this case, I think you are right @dcjones, someone may as well just put the benchmarks in an obvious place with the relevant additional info - machine, date, software versions, etc.

When people are no longer convinced by it then it can be swapped out for newer stuff.

AFAIU there is no other meaning to comparing BioJulia performance to other libraries, unless participating in an arms race is one of the goals of this project.

**Comment by Ward9250** [comment] 2015-11-12 23:55
Whilst the fact we can do operations faster than some other projects I don't think it's our main selling point. If you give that much care and focus on speed above all else well then C or lower to the metal would be what you want because C is still faster than Julia - the selling point the the closing of the speed gap between high level dynamic languages and the faster languages like C or C++. The gap is closed, and a researcher can prototype and optimise in the same language, and the language is much more readable and familiar to much more researchers already familiar with R, Python, and Matlab. The reseacher doesen't have the bother of interfacting two languages, which let's face it for open science is a bind - I have never met a single reviewer that knows A). My academic subject enough, B). The language I prototype an analysis or package in, C). The second language used for performance upgrades, and D). How the interfacing of the languages is done. I'm sure they exist, but they are few and far between.

**Closed** 2020-05-26 23:04 UTC
